- hosts: gerrit_host
  vars:
   db_type: "H2"  # options: H2, MYSQL, PSQL, ORACLE
   db_name: "db/ReviewDB"
   db_host: "{{gerrit_db_host}}" # assumes this alias is in the inventory file
   db_user: "root"
   db_password: "password"
  roles:
    - common
#    - mysql
#    - gerrit

